apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{.Values.imageRegistry}}/api-browser:main
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    app: {{.Release.Name}}
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}
  annotations:
    kubernetes.io/ingress.class: "public"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{.Values.deploymentHost}}
      http:
        paths:
          - path: /{{.Release.Name}}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}
                port:
                  number: 80



